name: Run Python Code

on:
  schedule:
    - cron: '0,20,40 * * * *' # 24마다 시간 실행
  workflow_dispatch:

jobs:
  run-code:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install system dependencies
        run: sudo apt-get update && sudo apt-get install -y build-essential libffi-dev

      - name: Install Python dependencies
        run: |
          pip install -r requirements.txt

      - name: Run Python script
        run: python main.py ${{secrets.MUSIC}} ${{secrets.BASIC}} ${{secrets.INFO}} ${{secrets.TELEGRAM}} ${{secrets.CHAT}} # 이곳에 실제 파이썬 파일명을 적어주세요.

      - name: Commit and push changes
        if: steps.changed-files.outputs.files_changed == 'true'
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Update from Github action"
          git push https://${{ secrets.GH_TOKEN }}@github.com/harukawa-sora/es-leak.git HEAD:main

        env:
          pythonLocation: /opt/hostedtoolcache/Python/3.11.3/x64
          LD_LIBRARY_PATH: /opt/hostedtoolcache/Python/3.11.3/x64/lib
